# Project: Joshua
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Joshua.o
LINKOBJ  = Joshua.o
LIBS     = -L"D:/ecodeLabs Dev/installed/Dev-Cpp/MinGW64/lib" -L"D:/ecodeLabs Dev/installed/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/ecodeLabs Dev/installed/Dev-Cpp/MinGW64/include" -I"D:/ecodeLabs Dev/installed/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/ecodeLabs Dev/installed/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/ecodeLabs Dev/installed/Dev-Cpp/MinGW64/include" -I"D:/ecodeLabs Dev/installed/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/ecodeLabs Dev/installed/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/ecodeLabs Dev/installed/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Joshua.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Joshua.o: Joshua.cpp
	$(CPP) -c Joshua.cpp -o Joshua.o $(CXXFLAGS)
